blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_blog, name='view_blog'),
    path('<int:blog_post_id>/',
         views.blog_post_detail,
         name='blog_post_detail'),
    path('add_blog_post/', views.add_blog_post, name='add_blog_post'),
    path('edit_blog_post/<int:blog_post_id>/',
         views.edit_blog_post, name='edit_blog_post'),
    path('delete_blog_post/<int:blog_post_id>/',
         views.delete_blog_post, name='delete_blog_post'),
    path('add_comment/<int:blog_post_id>/',
         views.add_blog_post_comment, name='add_blog_post_comment'),
    path('comment_approve/<int:comment_id>/',
         views.comment_approve, name='comment_approve'),
    path('comment_remove/<int:comment_id>',
         views.comment_remove, name='comment_remove'),
    path('edit_comment/<int:comment_id>',
         views.edit_comment, name='edit_comment'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

savasana_yoga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime

# Create your models here.


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=250)
    friendly_name = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):

    class Meta:
        ordering = ['day']

    DAYS_OF_THE_WEEK = [
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
        ('6', 'Saturday'),
        ('7', 'Sunday')
    ]

    category = models.ForeignKey(
        'Category', null=True, blank=True,
        on_delete=models.SET_NULL)
    name = models.CharField(max_length=250)
    day = models.CharField(
        max_length=10,
        choices=DAYS_OF_THE_WEEK,
        default='1')
    class_time = models.TimeField(
        auto_now=False,
        auto_now_add=False,
        default=datetime.time(10, 0))
    description = models.TextField()
    tagline = models.CharField(
        max_length=250, null=True,
        blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    number_of_sessions = models.IntegerField(
        validators=[MaxValueValidator(50),
                    MinValueValidator(1)], default=10)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import (
    render, redirect, reverse, HttpResponse, get_object_or_404
)

from django.contrib import messages

from products.models import Product

# Create your views here.


def view_cart(request):
    """ A view that renders the cart contents page """

    return render(request, 'cart/cart.html')


def add_to_cart(request, item_id):
    """ A view to add quantity of an item to the shopping cart
        Submits form to this view incl quantity and item_id
        Creates cart variable if it doesn't exist, or gets it from the session,
        Either adds the item to the cart, if it doesn't exist, or updates the
        quantity if it already exists.
        Finally overwrites the cart variable with the new updated cart
    """
    product = get_object_or_404(Product, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    redirect_url = request.POST.get('redirect_url')
    cart = request.session.get('cart', {})

    if item_id in list(cart.keys()):
        cart[item_id] += quantity
        messages.success(
            request, f'Updated {product.name} quantity to {cart[item_id]}'
        )
    else:
        cart[item_id] = quantity
        messages.success(request, f'Added {product.name} to your cart')

    request.session['cart'] = cart
    return redirect(redirect_url)


def adjust_cart(request, item_id):
    """ A view to adjust the number of items to a specified amount """

    product = get_object_or_404(Product, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    cart = request.session.get('cart', {})

    if quantity > 0:
        cart[item_id] = quantity
        messages.success(
            request, f'Updated {product.name} quantity to {cart[item_id]}'
        )
    else:
        cart.pop(item_id)
        messages.success(request, f'Removed {product.name} from your cart')

    request.session['cart'] = cart
    return redirect(reverse('view_cart'))


def remove_from_cart(request, item_id):
    """ A view to remove an item from the shopping cart """

    try:
        product = get_object_or_404(Product, pk=item_id)
        cart = request.session.get('cart', {})
        cart.pop(item_id)
        messages.success(request, f'Removed {product.name} from your cart')

        request.session['cart'] = cart
        return HttpResponse(status=200)

    except Exception as e:
        messages.error(request, f'Error removing item: {e}')
        return HttpResponse(status=500)

cart/templates/cart/cart-total.html
<h6>
    <strong>Cart Total: €{{ grand_total|floatformat:2 }}</strong>
</h6>

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block content %}


<div class="container mt-3 mb-2">
    <div class="row">
        <div class="col text-center mt-2 mb-1">
            <hr>
            <h2 class="logo-font">Shopping Cart</h2>
            <hr>
        </div>
    </div>
    <!-- Displays items in a user's shopping cart -->
    <div class="row">
        <div class="col">
            {% if cart_items %}
                    <div class="row">
                        <div class="col text-center">
                            {% include "cart/cart-total.html" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-center">
                            {% include "cart/checkout-buttons.html" %}
                            <p class="text-muted mt-2 mb-5">A summary of your shopping cart is below</p>
                        </div>
                    </div>
                    {% for item in cart_items %}
                        <div class="row">
                            <!-- Product Image -->
                            <div class="col-12 col-sm-6 mb-2">
                                {% include "cart/product-image.html" %}
                            </div>
                            <!-- Product Info -->
                            <div class="col-12 col-sm-6 mb-2">
                                {% include "cart/product-info.html" %}
                            </div>
                            <!-- Product Price -->
                            <div class="col-12 col-sm-6 order-sm-last">
                                <p class="my-0">Price: €{{ item.product.price }}</p>
                                <p><strong>Subtotal: </strong>€{{ item.product.price | calc_subtotal:item.quantity }}</p>
                            </div>
                            <!-- Quantity Form -->
                            <div class="col-12 col-sm-6">
                                {% include "cart/quantity-form.html" %}
                            </div>
                        </div>
                    
                        <div class="row">
                            <div class="col">
                                <hr>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p class="lead mb-5">Your cart is empty.</p>
                    <a href="{% url 'products' %}" class="btn back-btn rounded-1">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="text-uppercase">Browse Classes</span>
                    </a>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}

<!-- From Boutique Ado to add and remove quantity of products -->

<script>
    // Update quantity on click
    $('.update-link').click(function(e) {
        var form = $(this).prev('.update-form');
        form.submit();
    });

    // Remove item and reload on click
    $('.remove-item').click(function(e) {
        var csrfToken = "{{ csrf_token }}";
        var itemId = $(this).attr('id').split('remove_')[1];
        var url = `/cart/remove/${itemId}/`;
        var data = {'csrfmiddlewaretoken': csrfToken};

        $.post(url, data)
         .done(function() {
             location.reload();
         });
    });
</script>
{% endblock %}

cart/templates/cart/checkout-buttons.html
<!-- Buttons for a user to checkout the items in their shopping cart -->
<a href="{% url 'products' %}" class="btn back-btn rounded-1 mt-1">
    <span class="icon">
        <i class="fas fa-chevron-left"></i>
    </span>
    <span>Browse Classes</span>
</a>
<a href="{% url 'checkout' %}" class="btn cta-btn rounded-1 mt-1">
    <span>Secure Checkout</span>
    <span class="icon">
        <i class="fas fa-lock"></i>
    </span>
</a>

cart/templates/cart/product-image.html
{% if item.product.image %}
    <img class="img-fluid rounded product-cart-img" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
{% else %}
    <img class="img-fluid rounded product-cart-img" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
{% endif %}

cart/templates/cart/product-info.html
<p class="my-0"><strong>{{ item.product.name }}</strong></p>
<p class="my-0 small text-muted">Day: {{ item.product.get_day_display }}</p>
<p class="my-0 small text-muted">Time: {{ item.product.class_time }}</p>

cart/templates/cart/quantity-form.html
<form class="form update-form" method="POST" action="{% url 'adjust_cart' item.item_id %}">
    <!-- Form to adjust the qty of items in a user's shopping cart -->
    {% csrf_token %}
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
                <button class="decrement-qty btn btn-sm" 
                    data-item_id="{{ item.item_id }}" id="decrement-qty_{{ item.item_id }}">
                    <span>
                        <i class="fas fa-minus fa-sm"></i>
                    </span>
                </button>
            </div>
            <input class="form-control form-control-sm qty_input" type="number"
                name="quantity" value="{{ item.quantity }}" min="1" max="99"
                data-item_id="{{ item.item_id }}"
                id="id_qty_{{ item.item_id }}">
            <div class="input-group-append">
                <button class="increment-qty btn btn-sm"
                    data-item_id="{{ item.item_id }}" id="increment-qty_{{ item.item_id }}">
                    <span>
                        <i class="fas fa-plus fa-sm"></i>
                    </span>
                </button>
            </div>
        </div>
    </div>
</form>
<a class="update-link text-info mt-1"><small>Update</small></a>
<a class="remove-item text-danger mt-1" id="remove_{{ item.item_id }}"><small>Remove</small></a>